# Use the official .NET 10 SDK image
image: mcr.microsoft.com/dotnet/sdk:10.0

# Define the order of stages
stages:
  - build
  - test
  - publish

# Define a job for the build stage
build_project:
  stage: build
  script:
    - echo "Building the .NET project..."
    - dotnet build

# Define a job for the test stage
test_project:
  stage: test
  script:
    - echo "Running tests..."
    - dotnet test

# Define a job for the publish stage
publish_project:
  stage: publish
  script:
    - echo "Publishing the application in Release mode..."
    # -c Release betyder att koden optimeras för produktion
    # -o ./publish betyder att filerna läggs i en mapp som heter "publish"
    - dotnet publish -c Release -o ./publish
  artifacts:
    paths:
      - ./publish # Berätta för GitLab att spara den här mappen
    expire_in: 1 week # Filerna raderas automatiskt efter 1 vecka för att spara lagringsutrymme på GitLab
